- name: errorlog path group
  class: group
  group: path
  members:
    - meta: PATH
      path: /xyz/openbmc_project/logging/sel

- name: pathwatch errorlog
  class: pathwatch
  pathwatch: path
  paths: errorlog path group
  pathcallback: create errorlog trap

- name: create errorlog trap
  class: pathcallback
  pathcallback: eventpath
  paths: errorlog path group
  eventType: ErrorTrap
